-- ============================================================================
-- Extract multi-ingredient weather features from WeatherNext Graph
-- ============================================================================
-- Two-stage approach for cost optimization:
--   1. Pre-compute AOI geometry as a DECLARE variable (enables cluster pruning)
--   2. Filter rows using geography cluster index BEFORE UNNEST(forecast)
--
-- The WeatherNext table is:
--   - Partitioned by init_time (DAY)
--   - Clustered by geography
-- ============================================================================

-- ┌─────────────────────────────────────────────────────────┐
-- │  CONFIGURATION                                          │
-- └─────────────────────────────────────────────────────────┘
DECLARE gcp_project      STRING          DEFAULT 'YOUR_GCP_PROJECT';
DECLARE dataset_name     STRING          DEFAULT 'weathernext_demo';
DECLARE weathernext_tbl  STRING          DEFAULT 'YOUR_PROJECT.weathernext_graph_forecasts.59572747_4_0';

-- Area of interest: list of 5-digit county FIPS codes
DECLARE county_fips      ARRAY<STRING>   DEFAULT ['01051', '01101'];

-- Time window for valid forecast times
DECLARE start_ts         TIMESTAMP       DEFAULT TIMESTAMP('2024-05-06 00:00:00');
DECLARE end_ts           TIMESTAMP       DEFAULT TIMESTAMP('2024-05-15 00:00:00');

-- Specific lead hours to extract (6h increments matching WeatherNext resolution)
DECLARE lead_hours_arr   ARRAY<INT64>    DEFAULT [24, 30, 36, 42, 48];

-- Explicit init timestamps for partition pruning (generated by pipeline.py)
DECLARE init_timestamps  ARRAY<TIMESTAMP> DEFAULT [TIMESTAMP('2024-05-04 00:00:00')];

-- Spatial buffer around county boundaries (meters)
DECLARE spatial_buffer_m INT64           DEFAULT 25000;

-- Output table name
DECLARE output_table     STRING          DEFAULT 'graph_multi_ingredients_hourly';

-- Runtime variable: pre-computed AOI for cluster pruning
DECLARE target_aoi GEOGRAPHY;

-- ┌─────────────────────────────────────────────────────────┐
-- │  STEP 1: Compute AOI (enables cluster pruning)          │
-- └─────────────────────────────────────────────────────────┘

EXECUTE IMMEDIATE FORMAT("""
  SELECT ST_UNION_AGG(ST_BUFFER(county_geom, @spatial_buffer_m))
  FROM `%s.%s.counties_ref`
  WHERE county_fips_code IN UNNEST(@county_fips)
""",
  gcp_project, dataset_name
)
INTO target_aoi
USING
  spatial_buffer_m AS spatial_buffer_m,
  county_fips AS county_fips;

-- ┌─────────────────────────────────────────────────────────┐
-- │  STEP 2: Extract weather features (cluster-pruned)      │
-- └─────────────────────────────────────────────────────────┘

EXECUTE IMMEDIATE FORMAT("""
  CREATE OR REPLACE TABLE `%s.%s.%s`
  PARTITION BY DATE(hour_ts)
  CLUSTER BY county_fips, lead_hours
  AS

  WITH counties AS (
    SELECT county_fips_code, county_name, county_geom
    FROM `%s.%s.counties_ref`
    WHERE county_fips_code IN UNNEST(@county_fips)
  ),

  -- Filter using cluster index BEFORE UNNEST (critical for cost)
  filtered_cells AS (
    SELECT t.init_time, t.geography_polygon, t.forecast
    FROM `%s` AS t
    WHERE ST_INTERSECTS(t.geography, @target_aoi)
      AND t.init_time IN UNNEST(@init_timestamps)
  ),

  raw AS (
    SELECT
      fc.init_time,
      f.time                          AS valid_time,
      f.hours                         AS lead_hours,
      TIMESTAMP_TRUNC(f.time, HOUR)   AS hour_ts,

      -- 10m wind
      f.`10m_u_component_of_wind`     AS u10,
      f.`10m_v_component_of_wind`     AS v10,

      -- 925 hPa wind
      f.`925_u_component_of_wind`     AS u925,
      f.`925_v_component_of_wind`     AS v925,

      -- 500 hPa wind (for shear calculation)
      f.`500_u_component_of_wind`     AS u500,
      f.`500_v_component_of_wind`     AS v500,

      -- 700 hPa vertical velocity (updraft proxy)
      f.`700_vertical_velocity`       AS omega700,

      -- Temperature
      f.`700_temperature`             AS t700_k,
      f.`850_temperature`             AS t850_k,

      -- Precipitation
      f.total_precipitation_6hr       AS tp6_m,

      fc.geography_polygon            AS cell_geom

    FROM filtered_cells AS fc
    CROSS JOIN UNNEST(fc.forecast) AS f
    WHERE f.time >= @start_ts
      AND f.time <  @end_ts
      AND f.hours IN UNNEST(@lead_hours_arr)
  ),

  cell_features AS (
    SELECT
      hour_ts,
      lead_hours,
      cell_geom,

      -- Wind speeds
      SQRT(POW(u10, 2) + POW(v10, 2))               AS ws10_mps,
      SQRT(POW(u925, 2) + POW(v925, 2))              AS ws925_mps,

      -- 0-6 km shear (proxy using 500 hPa - 10m)
      SQRT(POW(u500 - u10, 2) + POW(v500 - v10, 2)) AS shear_0_6km_mps,

      -- Updraft proxy: positive upward vertical velocity at 700 hPa
      GREATEST(0.0, -omega700)                        AS updraft700_pos_pas,

      -- Temperature in Celsius
      (t700_k - 273.15)                               AS t700_c,
      (t850_k - 273.15)                               AS t850_c,

      -- Precipitation in mm
      COALESCE(tp6_m, 0.0) * 1000.0                  AS tp6_mm

    FROM raw
  )

  SELECT
    c.county_fips_code                AS county_fips,
    c.county_name,
    f.hour_ts,
    f.lead_hours,

    -- Wind aggregations (max across grid cells in county)
    MAX(f.ws10_mps)                   AS ws10_max_mps,
    MAX(f.ws925_mps)                  AS ws925_max_mps,
    MAX(f.shear_0_6km_mps)           AS shear_0_6km_max_mps,
    MAX(f.updraft700_pos_pas)         AS updraft700_pos_max_pas,

    -- Temperature (min for freezing level, mean for context)
    MIN(f.t700_c)                     AS t700_c_min,
    AVG(f.t700_c)                     AS t700_c_mean,
    AVG(f.t850_c)                     AS t850_c_mean,

    -- Precipitation
    MAX(f.tp6_mm)                     AS tp6_mm_max,
    AVG(f.tp6_mm)                     AS tp6_mm_mean

  FROM cell_features f
  JOIN counties c
    ON ST_INTERSECTS(f.cell_geom, ST_BUFFER(c.county_geom, @spatial_buffer_m))
  GROUP BY county_fips, county_name, hour_ts, lead_hours
""",
  gcp_project, dataset_name, output_table,
  gcp_project, dataset_name,
  weathernext_tbl
)
USING
  county_fips AS county_fips,
  target_aoi AS target_aoi,
  init_timestamps AS init_timestamps,
  start_ts AS start_ts,
  end_ts AS end_ts,
  lead_hours_arr AS lead_hours_arr,
  spatial_buffer_m AS spatial_buffer_m;
